[project]
name = "mcp-pr-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "anyio>=4.9.0",
    "mcp>=1.11.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]
